const manuscriptConstants = {
  FETCHING_MANUSCRIPTS: 'FETCHING_MANUSCRIPTS',
  FETCH_MANUSCRIPTS_SUCCESS: 'FETCH_MANUSCRIPTS_SUCCESS',
  FETCH_MANUSCRIPTS_FAILURE: 'FETCH_MANUSCRIPTS_FAILURE',

  FETCHING_MANUSCRIPT: 'FETCHING_MANUSCRIPT',
  FETCH_MANUSCRIPT_SUCCESS: 'FETCH_MANUSCRIPT_SUCCESS',
  FETCH_MANUSCRIPT_FAILURE: 'FETCH_MANUSCRIPT_FAILURE',
};

export default manuscriptConstants;
