const saintsLegendConstants = {
  FETCHING_SAINTS_LEGENDS: 'FETCHING_SAINTS_LEGENDS',
  FETCH_SAINTS_LEGENDS_SUCCESS: 'FETCH_SAINTS_LEGENDS_SUCCESS',
  FETCH_SAINTS_LEGENDS_FAILURE: 'FETCH_SAINTS_LEGENDS_FAILURE',

  FETCHING_SAINTS_LEGEND: 'FETCHING_SAINTS_LEGEND',
  FETCH_SAINTS_LEGEND_SUCCESS: 'FETCH_SAINTS_LEGEND_SUCCESS',
  FETCH_SAINTS_LEGEND_FAILURE: 'FETCH_SAINTS_LEGEND_FAILURE',
};

export default saintsLegendConstants;
