const witnessConstants = {
  FETCHING_WITNESSES: 'FETCHING_WITNESSES',
  FETCH_WITNESSES_SUCCESS: 'FETCH_WITNESSES_SUCCESS',
  FETCH_WITNESSES_FAILURE: 'FETCH_WITNESSES_FAILURE',
};

export default witnessConstants;
